# Generated by Django 4.0.2 on 2022-02-06 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo', models.ImageField(upload_to='logos')),
                ('is_recruiting', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('loading_city', models.CharField(max_length=128)),
                ('unloading_city', models.CharField(max_length=128)),
                ('loading_spedition', models.CharField(blank=True, max_length=128)),
                ('unloading_spedition', models.CharField(blank=True, max_length=128)),
                ('cargo', models.CharField(max_length=64)),
                ('tonnage', models.PositiveSmallIntegerField(default=0)),
                ('fuel', models.PositiveSmallIntegerField(default=0)),
                ('distance', models.PositiveSmallIntegerField(default=0)),
                ('income', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('Zaakceptowana', 'accepted'), ('Do poprawy', 'edit'), ('Odrzucona', 'rejected'), ('Wysłana', 'sent')], default='Wysłana', max_length=16)),
                ('is_edited', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=128)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_city', models.CharField(max_length=128)),
                ('unloading_city', models.CharField(max_length=128)),
                ('loading_spedition', models.CharField(max_length=128)),
                ('unloading_spedition', models.CharField(max_length=128)),
                ('cargo', models.CharField(max_length=64)),
                ('tonnage', models.PositiveSmallIntegerField(default=0)),
                ('income', models.PositiveIntegerField(default=0)),
                ('trailer', models.CharField(choices=[('Plandeka', 'curtain'), ('Chłodnia', 'reefer'), ('Niskopodłogowa', 'flatbed'), ('Kłonicowa', 'logger'), ('Wywrotka', 'tipper'), ('Kontener', 'container')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('MAN', 'man'), ('Mercedes-Benz', 'mercedes'), ('Scania', 'scania'), ('Volvo', 'volvo'), ('DAF', 'daf'), ('Renault', 'renault'), ('IVECO', 'iveco')], max_length=24)),
                ('model', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='vehicles')),
                ('cabin', models.CharField(max_length=10)),
                ('engine', models.PositiveSmallIntegerField(default=0)),
                ('chassis', models.CharField(default='4x2', max_length=3)),
                ('odometer', models.PositiveIntegerField(default=0)),
                ('license_plate', models.CharField(max_length=10)),
                ('is_drawed', models.BooleanField(default=False)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.company')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('Właściciel', 'owner'), ('Szef', 'boss'), ('Spedytor', 'speditor'), ('Kierowca', 'driver')], default='Kierowca', max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.company')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_city', models.CharField(max_length=128)),
                ('unloading_city', models.CharField(max_length=128)),
                ('loading_spedition', models.CharField(blank=True, max_length=128)),
                ('unloading_spedition', models.CharField(blank=True, max_length=128)),
                ('cargo', models.CharField(max_length=64)),
                ('tonnage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='waybills/')),
                ('delivery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.delivery')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.driver'),
        ),
    ]
